(define (domain aliens1)
(:requirements :typing :durative-actions :fluents :duration-inequalities)

(:predicates
	(london-bombed)
	(p1_0)
	(p1_4)
	(sf-bombed)
	(first-time)
	(p1_9)
	(p1_11)
	(p1_20)
	(p1_21)
	(p1_7)
	(p1_18)
	(drone2-undocking)
	(p1_2)
	(paris-bombed)
	(p1_22)
	(ny-bombed)
	(ship-fly-none)
	(p1_14)
	(p1_5)
	(p1_12)
	(p1_15)
	(above-whitehouse)
	(rome-bombed)
	(drone2-fly)
	(drone2-first-undock)
	(p1_10)
	(p1_24)
	(drone1-fly)
	(drone1-undocking)
	(ship-fly-two)
	(invasion-ongoing)
	(p1_13)
	(invasion-started)
	(p1_17)
	(p1)
	(drone2-busy)
	(drone1-first-undock)
	(p1_3)
	(p1_19)
	(drone1-busy)
	(p1_1)
	(p1_6)
	(ship-fly-one)
	(p1_8)
	(ship-fly)
	(p1_16)
	(p1_23)
)

(:functions
	(ship-y)
	(drone2-y)
	(drone1-y)
	(drone2-x)
	(drone1-x)
	(ship-x)
)

(:control-variable warp-speed
	:bounds (and (>= ?value -10000000.0) (<= ?value 10000000.0))
)
(:control-variable vx-drone2
	:bounds (and (>= ?value -20.0) (<= ?value 20.0))
)
(:control-variable vx-ship
	:bounds (and (>= ?value -20.0) (<= ?value 20.0))
)
(:control-variable vx-drone1
	:bounds (and (>= ?value -20.0) (<= ?value 20.0))
)
(:control-variable vy-ship
	:bounds (and (>= ?value -20.0) (<= ?value 20.0))
)
(:control-variable vy-drone2
	:bounds (and (>= ?value -20.0) (<= ?value 20.0))
)
(:control-variable vy-drone1
	:bounds (and (>= ?value -20.0) (<= ?value 20.0))
)



(:region ny-region
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (682 782) :width 32 :height 32))
)
(:region earth
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (0 0) :width 1280 :height 1024))
)
(:region wdc-region
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (982 482) :width 32 :height 32))
)
(:region rome-region
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (332 382) :width 32 :height 32))
)
(:region ship-range
	:parameters (?x1 ?y1 ?x2 ?y2)
	:condition (and (max-distance ((?x1 ?y1) (?x2 ?y2)) :d 24))
)
(:region paris-region
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (732 82) :width 32 :height 32))
)
(:region sf-region
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (1132 102) :width 32 :height 32))
)
(:region london-region
	:parameters (?x ?y)
	:condition (and (in-rect (?x ?y) :corner (92 182) :width 32 :height 32))
)

(:physical default
	:regions ()
	:parameters (0.05)
)

(:durative-action start-invasion_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (invasion-ongoing)))
		(at start (not (london-bombed)))
		(at start (not (paris-bombed)))
		(at start (not (rome-bombed)))
		(at start (not (sf-bombed)))
		(at start (not (ny-bombed)))
		(at start (first-time))
		(at start (not (invasion-started)))
		(at start (p1))
	)
	:effect (and
		(at start (not (first-time)))
		(at end (invasion-ongoing))
	)
)
(:durative-action undock-drone2_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone2-first-undock))
		(at start (not (drone2-fly)))
		(at start (not (drone2-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (drone2-fly))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_3))
	)
	:effect (and
		(at start (drone2-undocking))
		(at end (not (drone2-undocking)))
		(at end (not (drone2-first-undock)))
		(increase (drone2-x) (* 1 (warp-speed) #t))
		(increase (drone2-y) (* 1 (warp-speed) #t))
		(at start (not (p1_3)))
		(at start (p1_4))
	)
)
(:durative-action fly-drone2_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone2-x) (drone2-y))))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (drone2-undocking))
		(at start (not (drone2-fly)))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (not (drone2-busy)))
		(at start (p1))
	)
	:effect (and
		(at start (drone2-fly))
		(at end (not (drone2-fly)))
		(increase (drone2-x) (* 1 (vx-drone2) #t))
		(increase (drone2-y) (* 1 (vy-drone2) #t))
	)
)
(:durative-action undock-drone2_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone2-first-undock))
		(at start (not (drone2-fly)))
		(at start (not (drone2-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (drone2-fly))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_3))
		(at end (not (p1_5)))
	)
	:effect (and
		(at start (drone2-undocking))
		(at end (not (drone2-undocking)))
		(at end (not (drone2-first-undock)))
		(increase (drone2-x) (* 1 (warp-speed) #t))
		(increase (drone2-y) (* 1 (warp-speed) #t))
		(at start (not (p1_3)))
		(at start (p1_4))
		(at end (p1))
	)
)
(:durative-action bomb-london2_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (london-bombed)))
		(over all (inside (london-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at start (not (p1_6)))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (london-bombed))
		(at start (p1))
	)
)
(:durative-action fly-drone2_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone2-x) (drone2-y))))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (drone2-undocking))
		(at start (not (drone2-fly)))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (not (drone2-busy)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_4))
		(at end (not (p1_20)))
	)
	:effect (and
		(at start (drone2-fly))
		(at end (not (drone2-fly)))
		(increase (drone2-x) (* 1 (vx-drone2) #t))
		(increase (drone2-y) (* 1 (vy-drone2) #t))
		(at start (not (p1_4)))
		(at start (p1_5))
		(at end (p1))
	)
)
(:durative-action threat-whitehouse_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(over all (inside (wdc-region (ship-x) (ship-y))))
		(at start (london-bombed))
		(at start (paris-bombed))
		(at start (rome-bombed))
		(at start (ny-bombed))
		(at start (sf-bombed))
		(at start (not (p1)))
		(at start (not (p1_22)))
	)
	:effect (and
		(at end (not (invasion-ongoing)))
		(at end (above-whitehouse))
		(at start (p1))
	)
)
(:durative-action undock-drone2_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone2-first-undock))
		(at start (not (drone2-fly)))
		(at start (not (drone2-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (drone2-fly))
		(at start (p1))
	)
	:effect (and
		(at start (drone2-undocking))
		(at end (not (drone2-undocking)))
		(at end (not (drone2-first-undock)))
		(increase (drone2-x) (* 1 (warp-speed) #t))
		(increase (drone2-y) (* 1 (warp-speed) #t))
	)
)
(:durative-action bomb-london2_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (london-bombed)))
		(over all (inside (london-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_6))
		(at end (p1_7))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (london-bombed))
		(at start (not (p1_6)))
		(at start (p1_7))
		(at end (not (p1_7)))
		(at end (p1_8))
	)
)
(:durative-action bomb-rome2_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (rome-bombed)))
		(over all (inside (rome-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (p1))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (rome-bombed))
	)
)
(:durative-action bomb-paris1_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (paris-bombed)))
		(over all (inside (paris-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (p1))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (paris-bombed))
	)
)
(:durative-action threat-whitehouse_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(over all (inside (wdc-region (ship-x) (ship-y))))
		(at start (london-bombed))
		(at start (paris-bombed))
		(at start (rome-bombed))
		(at start (ny-bombed))
		(at start (sf-bombed))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_22))
		(at end (p1_23))
	)
	:effect (and
		(at end (not (invasion-ongoing)))
		(at end (above-whitehouse))
		(at start (not (p1_22)))
		(at start (p1_23))
		(at end (not (p1_23)))
		(at end (p1_24))
	)
)
(:durative-action bomb-sf2_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (sf-bombed)))
		(over all (inside (sf-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_18))
		(at end (p1_19))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (sf-bombed))
		(at start (not (p1_18)))
		(at start (p1_19))
		(at end (not (p1_19)))
		(at end (p1_20))
	)
)
(:durative-action bomb-rome2_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (rome-bombed)))
		(over all (inside (rome-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_8))
		(at end (not (p1_9)))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (rome-bombed))
		(at start (not (p1_8)))
		(at start (p1_9))
		(at end (p1))
	)
)
(:durative-action undock-drone2_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone2-first-undock))
		(at start (not (drone2-fly)))
		(at start (not (drone2-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (drone2-fly))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_3))
		(at end (p1_5))
	)
	:effect (and
		(at start (drone2-undocking))
		(at end (not (drone2-undocking)))
		(at end (not (drone2-first-undock)))
		(increase (drone2-x) (* 1 (warp-speed) #t))
		(increase (drone2-y) (* 1 (warp-speed) #t))
		(at start (not (p1_3)))
		(at start (p1_4))
		(at end (not (p1_5)))
		(at end (p1_6))
	)
)
(:durative-action bomb-rome2_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (rome-bombed)))
		(over all (inside (rome-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at start (not (p1_8)))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (rome-bombed))
		(at start (p1))
	)
)
(:durative-action fly-ship_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(over all (invasion-ongoing))
		(over all (inside (earth (ship-x) (ship-y))))
		(at start (not (ship-fly)))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_2))
		(at end (not (p1_21)))
	)
	:effect (and
		(increase (ship-x) (* 1 (vx-ship) #t))
		(increase (ship-y) (* 1 (vy-ship) #t))
		(at start (ship-fly))
		(at end (not (ship-fly)))
		(at start (invasion-started))
		(at start (not (p1_2)))
		(at start (p1_3))
		(at end (p1))
	)
)
(:durative-action bomb-sf2_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (sf-bombed)))
		(over all (inside (sf-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_18))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (sf-bombed))
		(at start (not (p1_18)))
		(at start (p1_19))
	)
)
(:durative-action undock-drone1_121
	:parameters ()
	:duration (and (>= ?duration 0.01) (<= ?duration 0.03))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone1-first-undock))
		(at start (not (drone1-fly)))
		(at start (not (drone1-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (drone1-fly))
		(at start (not (p1)))
		(at start (not (p1_10)))
	)
	:effect (and
		(at start (drone1-undocking))
		(at end (not (drone1-undocking)))
		(at end (not (drone1-first-undock)))
		(increase (drone1-x) (* 1 (warp-speed) #t))
		(increase (drone1-y) (* 1 (warp-speed) #t))
		(at start (p1))
	)
)
(:durative-action fly-ship_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(over all (invasion-ongoing))
		(over all (inside (earth (ship-x) (ship-y))))
		(at start (not (ship-fly)))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at start (not (p1_2)))
	)
	:effect (and
		(increase (ship-x) (* 1 (vx-ship) #t))
		(increase (ship-y) (* 1 (vy-ship) #t))
		(at start (ship-fly))
		(at end (not (ship-fly)))
		(at start (invasion-started))
		(at start (p1))
	)
)
(:durative-action threat-whitehouse_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(over all (inside (wdc-region (ship-x) (ship-y))))
		(at start (london-bombed))
		(at start (paris-bombed))
		(at start (rome-bombed))
		(at start (ny-bombed))
		(at start (sf-bombed))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_22))
	)
	:effect (and
		(at end (not (invasion-ongoing)))
		(at end (above-whitehouse))
		(at start (not (p1_22)))
		(at start (p1_23))
	)
)
(:durative-action fly-drone1_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone1-x) (drone1-y))))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (drone1-undocking))
		(at start (not (drone1-fly)))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (not (drone1-busy)))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_11))
	)
	:effect (and
		(at start (drone1-fly))
		(at end (not (drone1-fly)))
		(increase (drone1-x) (* 1 (vx-drone1) #t))
		(increase (drone1-y) (* 1 (vy-drone1) #t))
		(at start (not (p1_11)))
		(at start (p1_12))
	)
)
(:durative-action bomb-ny1_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (ny-bombed)))
		(over all (inside (ny-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_15))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (ny-bombed))
		(at start (not (p1_15)))
		(at start (p1_16))
	)
)
(:durative-action bomb-london2_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (london-bombed)))
		(over all (inside (london-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_6))
		(at end (not (p1_7)))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (london-bombed))
		(at start (not (p1_6)))
		(at start (p1_7))
		(at end (p1))
	)
)
(:durative-action bomb-rome1_101
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (rome-bombed)))
		(over all (inside (rome-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (rome-bombed))
		(at start (p1))
	)
)
(:durative-action bomb-paris1_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (paris-bombed)))
		(over all (inside (paris-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at start (not (p1_13)))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (paris-bombed))
		(at start (p1))
	)
)
(:durative-action bomb-sf1_101
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (sf-bombed)))
		(over all (inside (sf-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (sf-bombed))
		(at start (p1))
	)
)
(:durative-action undock-drone1_131
	:parameters ()
	:duration (and (>= ?duration 0.01) (<= ?duration 0.03))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone1-first-undock))
		(at start (not (drone1-fly)))
		(at start (not (drone1-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (drone1-fly))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_10))
	)
	:effect (and
		(at start (drone1-undocking))
		(at end (not (drone1-undocking)))
		(at end (not (drone1-first-undock)))
		(increase (drone1-x) (* 1 (warp-speed) #t))
		(increase (drone1-y) (* 1 (warp-speed) #t))
		(at start (not (p1_10)))
		(at start (p1_11))
	)
)
(:durative-action bomb-rome2_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (rome-bombed)))
		(over all (inside (rome-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_8))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (rome-bombed))
		(at start (not (p1_8)))
		(at start (p1_9))
	)
)
(:durative-action threat-whitehouse_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(over all (inside (wdc-region (ship-x) (ship-y))))
		(at start (london-bombed))
		(at start (paris-bombed))
		(at start (rome-bombed))
		(at start (ny-bombed))
		(at start (sf-bombed))
		(at start (p1))
	)
	:effect (and
		(at end (not (invasion-ongoing)))
		(at end (above-whitehouse))
	)
)
(:durative-action fly-drone2_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone2-x) (drone2-y))))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (drone2-undocking))
		(at start (not (drone2-fly)))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (not (drone2-busy)))
		(at start (not (p1)))
		(at start (not (p1_4)))
	)
	:effect (and
		(at start (drone2-fly))
		(at end (not (drone2-fly)))
		(increase (drone2-x) (* 1 (vx-drone2) #t))
		(increase (drone2-y) (* 1 (vy-drone2) #t))
		(at start (p1))
	)
)
(:durative-action bomb-paris1_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (paris-bombed)))
		(over all (inside (paris-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_13))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (paris-bombed))
		(at start (not (p1_13)))
		(at start (p1_14))
	)
)
(:durative-action bomb-paris2_101
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (paris-bombed)))
		(over all (inside (paris-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (paris-bombed))
		(at start (p1))
	)
)
(:durative-action bomb-ny2_101
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (ny-bombed)))
		(over all (inside (ny-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (ny-bombed))
		(at start (p1))
	)
)
(:durative-action undock-drone1_111
	:parameters ()
	:duration (and (>= ?duration 0.01) (<= ?duration 0.03))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone1-first-undock))
		(at start (not (drone1-fly)))
		(at start (not (drone1-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (drone1-fly))
		(at start (p1))
	)
	:effect (and
		(at start (drone1-undocking))
		(at end (not (drone1-undocking)))
		(at end (not (drone1-first-undock)))
		(increase (drone1-x) (* 1 (warp-speed) #t))
		(increase (drone1-y) (* 1 (warp-speed) #t))
	)
)
(:durative-action start-invasion_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (invasion-ongoing)))
		(at start (not (london-bombed)))
		(at start (not (paris-bombed)))
		(at start (not (rome-bombed)))
		(at start (not (sf-bombed)))
		(at start (not (ny-bombed)))
		(at start (first-time))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_0))
		(at end (p1_1))
	)
	:effect (and
		(at start (not (first-time)))
		(at end (invasion-ongoing))
		(at start (not (p1_0)))
		(at start (p1_1))
		(at end (not (p1_1)))
		(at end (p1_2))
	)
)
(:durative-action fly-drone1_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone1-x) (drone1-y))))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (drone1-undocking))
		(at start (not (drone1-fly)))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (not (drone1-busy)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_11))
		(at end (p1_17))
	)
	:effect (and
		(at start (drone1-fly))
		(at end (not (drone1-fly)))
		(increase (drone1-x) (* 1 (vx-drone1) #t))
		(increase (drone1-y) (* 1 (vy-drone1) #t))
		(at start (not (p1_11)))
		(at start (p1_12))
		(at end (not (p1_17)))
		(at end (p1_18))
	)
)
(:durative-action start-invasion_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (invasion-ongoing)))
		(at start (not (london-bombed)))
		(at start (not (paris-bombed)))
		(at start (not (rome-bombed)))
		(at start (not (sf-bombed)))
		(at start (not (ny-bombed)))
		(at start (first-time))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_0))
	)
	:effect (and
		(at start (not (first-time)))
		(at end (invasion-ongoing))
		(at start (not (p1_0)))
		(at start (p1_1))
	)
)
(:durative-action bomb-ny1_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (ny-bombed)))
		(over all (inside (ny-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_15))
		(at end (not (p1_16)))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (ny-bombed))
		(at start (not (p1_15)))
		(at start (p1_16))
		(at end (p1))
	)
)
(:durative-action fly-ship_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(over all (invasion-ongoing))
		(over all (inside (earth (ship-x) (ship-y))))
		(at start (not (ship-fly)))
		(at start (not (invasion-started)))
		(at start (p1))
	)
	:effect (and
		(increase (ship-x) (* 1 (vx-ship) #t))
		(increase (ship-y) (* 1 (vy-ship) #t))
		(at start (ship-fly))
		(at end (not (ship-fly)))
		(at start (invasion-started))
	)
)
(:durative-action bomb-paris1_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (paris-bombed)))
		(over all (inside (paris-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_13))
		(at end (not (p1_14)))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (paris-bombed))
		(at start (not (p1_13)))
		(at start (p1_14))
		(at end (p1))
	)
)
(:durative-action bomb-london1_101
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(over all (invasion-ongoing))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (london-bombed)))
		(over all (inside (london-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (london-bombed))
		(at start (p1))
	)
)
(:durative-action bomb-paris1_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (paris-bombed)))
		(over all (inside (paris-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_13))
		(at end (p1_14))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (paris-bombed))
		(at start (not (p1_13)))
		(at start (p1_14))
		(at end (not (p1_14)))
		(at end (p1_15))
	)
)
(:durative-action bomb-sf2_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (sf-bombed)))
		(over all (inside (sf-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at start (not (p1_18)))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (sf-bombed))
		(at start (p1))
	)
)
(:durative-action fly-ship_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(over all (invasion-ongoing))
		(over all (inside (earth (ship-x) (ship-y))))
		(at start (not (ship-fly)))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_2))
		(at end (p1_21))
	)
	:effect (and
		(increase (ship-x) (* 1 (vx-ship) #t))
		(increase (ship-y) (* 1 (vy-ship) #t))
		(at start (ship-fly))
		(at end (not (ship-fly)))
		(at start (invasion-started))
		(at start (not (p1_2)))
		(at start (p1_3))
		(at end (not (p1_21)))
		(at end (p1_22))
	)
)
(:durative-action start-invasion_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (invasion-ongoing)))
		(at start (not (london-bombed)))
		(at start (not (paris-bombed)))
		(at start (not (rome-bombed)))
		(at start (not (sf-bombed)))
		(at start (not (ny-bombed)))
		(at start (first-time))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_0))
		(at end (not (p1_1)))
	)
	:effect (and
		(at start (not (first-time)))
		(at end (invasion-ongoing))
		(at start (not (p1_0)))
		(at start (p1_1))
		(at end (p1))
	)
)
(:durative-action undock-drone2_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone2-first-undock))
		(at start (not (drone2-fly)))
		(at start (not (drone2-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (drone2-fly))
		(at start (not (p1)))
		(at start (not (p1_3)))
	)
	:effect (and
		(at start (drone2-undocking))
		(at end (not (drone2-undocking)))
		(at end (not (drone2-first-undock)))
		(increase (drone2-x) (* 1 (warp-speed) #t))
		(increase (drone2-y) (* 1 (warp-speed) #t))
		(at start (p1))
	)
)
(:durative-action bomb-london2_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (london-bombed)))
		(over all (inside (london-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_6))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (london-bombed))
		(at start (not (p1_6)))
		(at start (p1_7))
	)
)
(:durative-action bomb-sf2_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (sf-bombed)))
		(over all (inside (sf-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_18))
		(at end (not (p1_19)))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (sf-bombed))
		(at start (not (p1_18)))
		(at start (p1_19))
		(at end (p1))
	)
)
(:durative-action bomb-ny1_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (ny-bombed)))
		(over all (inside (ny-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at start (not (p1_15)))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (ny-bombed))
		(at start (p1))
	)
)
(:durative-action bomb-london2_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (london-bombed)))
		(over all (inside (london-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (p1))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (london-bombed))
	)
)
(:durative-action bomb-ny1_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (ny-bombed)))
		(over all (inside (ny-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_15))
		(at end (p1_16))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (ny-bombed))
		(at start (not (p1_15)))
		(at start (p1_16))
		(at end (not (p1_16)))
		(at end (p1_17))
	)
)
(:durative-action fly-ship_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(over all (invasion-ongoing))
		(over all (inside (earth (ship-x) (ship-y))))
		(at start (not (ship-fly)))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_2))
	)
	:effect (and
		(increase (ship-x) (* 1 (vx-ship) #t))
		(increase (ship-y) (* 1 (vy-ship) #t))
		(at start (ship-fly))
		(at end (not (ship-fly)))
		(at start (invasion-started))
		(at start (not (p1_2)))
		(at start (p1_3))
	)
)
(:durative-action start-invasion_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (invasion-ongoing)))
		(at start (not (london-bombed)))
		(at start (not (paris-bombed)))
		(at start (not (rome-bombed)))
		(at start (not (sf-bombed)))
		(at start (not (ny-bombed)))
		(at start (first-time))
		(at start (not (invasion-started)))
		(at start (not (p1)))
		(at start (not (p1_0)))
	)
	:effect (and
		(at start (not (first-time)))
		(at end (invasion-ongoing))
		(at start (p1))
	)
)
(:durative-action bomb-ny1_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone1-busy)))
		(at end (drone1-busy))
		(at start (drone1-fly))
		(at end (drone1-fly))
		(over all (drone1-fly))
		(at start (not (ny-bombed)))
		(over all (inside (ny-region (drone1-x) (drone1-y))))
		(over all (invasion-ongoing))
		(at start (p1))
	)
	:effect (and
		(at start (drone1-busy))
		(at end (not (drone1-busy)))
		(at end (ny-bombed))
	)
)
(:durative-action fly-drone1_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone1-x) (drone1-y))))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (drone1-undocking))
		(at start (not (drone1-fly)))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (not (drone1-busy)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_11))
		(at end (not (p1_17)))
	)
	:effect (and
		(at start (drone1-fly))
		(at end (not (drone1-fly)))
		(increase (drone1-x) (* 1 (vx-drone1) #t))
		(increase (drone1-y) (* 1 (vy-drone1) #t))
		(at start (not (p1_11)))
		(at start (p1_12))
		(at end (p1))
	)
)
(:durative-action threat-whitehouse_141
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(over all (inside (wdc-region (ship-x) (ship-y))))
		(at start (london-bombed))
		(at start (paris-bombed))
		(at start (rome-bombed))
		(at start (ny-bombed))
		(at start (sf-bombed))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_22))
		(at end (not (p1_23)))
	)
	:effect (and
		(at end (not (invasion-ongoing)))
		(at end (above-whitehouse))
		(at start (not (p1_22)))
		(at start (p1_23))
		(at end (p1))
	)
)
(:durative-action bomb-sf2_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (sf-bombed)))
		(over all (inside (sf-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (p1))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (sf-bombed))
	)
)
(:durative-action fly-drone2_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone2-x) (drone2-y))))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (drone2-undocking))
		(at start (not (drone2-fly)))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (not (drone2-busy)))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_4))
		(at end (p1_20))
	)
	:effect (and
		(at start (drone2-fly))
		(at end (not (drone2-fly)))
		(increase (drone2-x) (* 1 (vx-drone2) #t))
		(increase (drone2-y) (* 1 (vy-drone2) #t))
		(at start (not (p1_4)))
		(at start (p1_5))
		(at end (not (p1_20)))
		(at end (p1_21))
	)
)
(:durative-action bomb-rome2_151
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 0.1))
	:condition (and
		(at start (not (drone2-busy)))
		(at end (drone2-busy))
		(at start (drone2-fly))
		(at end (drone2-fly))
		(over all (drone2-fly))
		(at start (not (rome-bombed)))
		(over all (inside (rome-region (drone2-x) (drone2-y))))
		(over all (invasion-ongoing))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_8))
		(at end (p1_9))
	)
	:effect (and
		(at start (drone2-busy))
		(at end (not (drone2-busy)))
		(at end (rome-bombed))
		(at start (not (p1_8)))
		(at start (p1_9))
		(at end (not (p1_9)))
		(at end (p1_10))
	)
)
(:durative-action undock-drone1_151
	:parameters ()
	:duration (and (>= ?duration 0.01) (<= ?duration 0.03))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone1-first-undock))
		(at start (not (drone1-fly)))
		(at start (not (drone1-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (drone1-fly))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_10))
		(at end (p1_12))
	)
	:effect (and
		(at start (drone1-undocking))
		(at end (not (drone1-undocking)))
		(at end (not (drone1-first-undock)))
		(increase (drone1-x) (* 1 (warp-speed) #t))
		(increase (drone1-y) (* 1 (warp-speed) #t))
		(at start (not (p1_10)))
		(at start (p1_11))
		(at end (not (p1_12)))
		(at end (p1_13))
	)
)
(:durative-action fly-drone2_131
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone2-x) (drone2-y))))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (drone2-undocking))
		(at start (not (drone2-fly)))
		(over all (inside (earth (drone2-x) (drone2-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone2-x) (drone2-y))))
		(at end (not (drone2-busy)))
		(at start (not (p1)))
		(at end (p1))
		(at start (p1_4))
	)
	:effect (and
		(at start (drone2-fly))
		(at end (not (drone2-fly)))
		(increase (drone2-x) (* 1 (vx-drone2) #t))
		(increase (drone2-y) (* 1 (vy-drone2) #t))
		(at start (not (p1_4)))
		(at start (p1_5))
	)
)
(:durative-action undock-drone1_141
	:parameters ()
	:duration (and (>= ?duration 0.01) (<= ?duration 0.03))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (drone1-first-undock))
		(at start (not (drone1-fly)))
		(at start (not (drone1-undocking)))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (drone1-fly))
		(at start (not (p1)))
		(at end (not (p1)))
		(at start (p1_10))
		(at end (not (p1_12)))
	)
	:effect (and
		(at start (drone1-undocking))
		(at end (not (drone1-undocking)))
		(at end (not (drone1-first-undock)))
		(increase (drone1-x) (* 1 (warp-speed) #t))
		(increase (drone1-y) (* 1 (warp-speed) #t))
		(at start (not (p1_10)))
		(at start (p1_11))
		(at end (p1))
	)
)
(:durative-action fly-drone1_111
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone1-x) (drone1-y))))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (drone1-undocking))
		(at start (not (drone1-fly)))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (not (drone1-busy)))
		(at start (p1))
	)
	:effect (and
		(at start (drone1-fly))
		(at end (not (drone1-fly)))
		(increase (drone1-x) (* 1 (vx-drone1) #t))
		(increase (drone1-y) (* 1 (vy-drone1) #t))
	)
)
(:durative-action fly-drone1_121
	:parameters ()
	:duration (and (>= ?duration 0.1) (<= ?duration 200.0))
	:condition (and
		(at start (invasion-ongoing))
		(at end (invasion-ongoing))
		(at start (ship-fly))
		(over all (ship-fly))
		(at end (ship-fly))
		(at start (inside (earth (drone1-x) (drone1-y))))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (drone1-undocking))
		(at start (not (drone1-fly)))
		(over all (inside (earth (drone1-x) (drone1-y))))
		(at start (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (inside (ship-range (ship-x) (ship-y) (drone1-x) (drone1-y))))
		(at end (not (drone1-busy)))
		(at start (not (p1)))
		(at start (not (p1_11)))
	)
	:effect (and
		(at start (drone1-fly))
		(at end (not (drone1-fly)))
		(increase (drone1-x) (* 1 (vx-drone1) #t))
		(increase (drone1-y) (* 1 (vy-drone1) #t))
		(at start (p1))
	)
)
)